#!/usr/bin/env bash
# tests/e2e/setup.sh — first-run secrets prompt for the Probe e2e suite.
#
# Run this ONCE on a fresh checkout. It writes tests/e2e/.env with the
# local-dev login password (read silently — never echoed, never logged,
# never sent anywhere). After this, `npm test` Just Works for any team
# member without further password handling.
#
# Re-run any time the password rotates.

set -euo pipefail

# Resolve the directory this script lives in, regardless of cwd.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env"

echo "Lifeplan e2e suite — local secrets setup"
echo "  Writing: $ENV_FILE"
echo

if [[ -f "$ENV_FILE" ]]; then
  read -r -p "  $ENV_FILE already exists. Overwrite? [y/N] " confirm
  case "${confirm:-N}" in
    y|Y|yes|YES) ;;
    *) echo "  Aborted. Existing file untouched."; exit 0 ;;
  esac
fi

# Silent prompt — no echo, no shell history, no log.
read -r -s -p "  Local-dev login password: " password
echo
if [[ -z "$password" ]]; then
  echo "  Empty password. Aborted." >&2
  exit 1
fi

read -r -s -p "  Confirm password: " password_confirm
echo
if [[ "$password" != "$password_confirm" ]]; then
  echo "  Passwords did not match. Aborted." >&2
  exit 1
fi

# Optional base URL override (Enter to accept default).
read -r -p "  Base URL [http://localhost:3131/]: " base_url
base_url="${base_url:-http://localhost:3131/}"

# Write atomically: temp file, chmod, mv.
TMP_FILE="$(mktemp "${ENV_FILE}.XXXXXX")"
trap 'rm -f "$TMP_FILE"' EXIT

cat > "$TMP_FILE" <<EOF
# tests/e2e/.env — generated by setup.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# DO NOT COMMIT. Gitignored. Re-run setup.sh to rotate.
LIFEPLAN_TEST_PASSWORD=$password
LIFEPLAN_TEST_BASE_URL=$base_url
EOF

chmod 600 "$TMP_FILE"
mv "$TMP_FILE" "$ENV_FILE"
trap - EXIT

# Defensive: clear the password from this shell's memory before exit.
password=""
password_confirm=""

echo
echo "  Wrote $ENV_FILE (mode 600)."
echo "  Probe is now self-serve. From $SCRIPT_DIR, run:"
echo "    npm test"
